[project]
name = "dotfiles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "invoke>=2.2.0",
    "pydantic>=2.11.7",
    "requests>=2.32.5",
    "rich>=14.1.0",
]
