# Main justfile - modular recipe organization
# Run `just --list` to see all available recipes

set quiet
set dotenv-load

import 'dev.just'

mod lua    # just/lua/mod.just -> lua::* or "just lua <recipe>"

default:
    just --list
